config/routes.rb
Rails.application.routes.draw do
	resources :restaurants do
		resources :reviews, only: [ :index, :new, :create]
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :reviews, dependent: :destroy
	validates :name, presence: true
	validates :address, presence: true
	validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant_id, presence: true
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController


	def index 
		@restaurants = Restaurant.all
	end

	def show
		@restaurant = Restaurant.find(params[:id])
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(restaurant_params)
		if @restaurant.save
			redirect_to restaurant_path(@restaurant)
		else
			render :new
		end
	end

	private

	def restaurant_params
		params.require(:restaurant).permit(:name, :address, :phone_number, :category)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_restaurant

	def index
		@reviews = @restaurant.reviews
	end

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.restaurant = @restaurant
    @review.save # Recall what ! does it here after save
    if @review.save
    	redirect_to restaurant_path(@restaurant)
    else
    	render :new
    end

end



private

def review_params
	params.require(:review).permit(:content, :rating)
end

def set_restaurant
	@restaurant = Restaurant.find(params[:restaurant_id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <head>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<hr>
<%= link_to "Add Restaurant", new_restaurant_path, class: "btn btn-primary" %>
<hr>

<% @restaurants.each do |restaurant| %>
  <p>Restaurant name: <strong><%= link_to restaurant.name, restaurant_path(restaurant) %></strong></p>
  <hr>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<hr>
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "Add a restaurant", class: "btn btn-primary" %>
<% end %>
<hr>

app/views/restaurants/show.html.erb
<h1>Restaurant List</h1>
<hr>
<%=link_to "List Restaurants", restaurants_path, class: "btn btn-primary" %>
<hr>
<p>name: <%= @restaurant.name %></p>
<p>address: <%= @restaurant.address %></p>
<p>phone: <%= @restaurant.phone_number %></p>
<p>category: <%= @restaurant.category %></p>
<hr>
<%= link_to "Add Review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
<%= link_to "Check Reviews", restaurant_reviews_path(@restaurant), class: "btn btn-primary" %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<hr>
<hr>
<% @reviews.each do |review| %>
  <p><%= review.content %></p>
  <p><%= review.rating %></p>
  <hr>
<% end %>
<%= link_to "Back to Restaurant", restaurant_path(@restaurant), class: "btn btn-primary" %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<hr>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Add a review", class: "btn btn-primary" %>
<% end %>
<hr>